name: Maestro Tests

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint Code
    type: custom
    steps:
      - run: bun run lint

  typecheck:
    name: Type Check
    type: custom
    steps:
      - run: ./node_modules/.bin/tsc --noEmit

  fingerprint:
    name: Calculate Fingerprint
    needs: [lint, typecheck]
    type: fingerprint
    environment: preview

  get_build:
    name: Check for Existing Build
    needs: [fingerprint]
    type: get-build
    params:
      platform: ios
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      simulator: true
      wait_for_in_progress: true

#  build:
#    name: Build iOS Simulator
#    needs: [get_build]
#    if: ${{ !needs.get_build.outputs.build_id }}
#    type: build
#    params:
#      platform: ios
#      profile: preview-simulator
#
#  maestro_test:
#    name: Run Maestro Tests
#    after: [get_build, build]
#    type: maestro
#    params:
#      build_id: ${{ needs.get_build.outputs.build_id || needs.build.outputs.build_id }}
#      flow_path: .maestro
#      retries: 1
